server:
  port: 8210
spring:
  servlet:
    multipart:
      max-file-size: -1MB
      max-request-size: -1MB
  application:
    # 应用名称
    name: gis-server
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      exclude: /static/**, /public/**
    livereload:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: 'health,metrics'
knife4j:
  enable: true
#  production: true